# src/schemas.py

# KRX 체결 (H0STCNT0) - 46 fields (실수신 기준)
COLUMNS_H0STCNT0 = [
    "MKSC_SHRN_ISCD","STCK_CNTG_HOUR","STCK_PRPR","PRDY_VRSS_SIGN",
    "PRDY_VRSS","PRDY_CTRT","WGHN_AVRG_STCK_PRC","STCK_OPRC",
    "STCK_HGPR","STCK_LWPR","ASKP1","BIDP1","CNTG_VOL","ACML_VOL",
    "ACML_TR_PBMN","SELN_CNTG_CSNU","SHNU_CNTG_CSNU","NTBY_CNTG_CSNU",
    "CTTR","SELN_CNTG_SMTN","SHNU_CNTG_SMTN","CCLD_DVSN","SHNU_RATE",
    "PRDY_VOL_VRSS_ACML_VOL_RATE","OPRC_HOUR","OPRC_VRSS_PRPR_SIGN",
    "OPRC_VRSS_PRPR","HGPR_HOUR","HGPR_VRSS_PRPR_SIGN","HGPR_VRSS_PRPR",
    "LWPR_HOUR","LWPR_VRSS_PRPR_SIGN","LWPR_VRSS_PRPR","BSOP_DATE",
    "NEW_MKOP_CLS_CODE","TRHT_YN","ASKP_RSQN1","BIDP_RSQN1",
    "TOTAL_ASKP_RSQN","TOTAL_BIDP_RSQN","VOL_TNRT",
    "PRDY_SMNS_HOUR_ACML_VOL","PRDY_SMNS_HOUR_ACML_VOL_RATE",
    "HOUR_CLS_CODE","MRKT_TRTM_CLS_CODE","VI_STND_PRC"
]

# NXT 체결 (H0NXCNT0) - 실수신에서 H0STCNT0와 동일 구조로 관측됨
COLUMNS_H0NXCNT0 = COLUMNS_H0STCNT0

# KRX 호가 (H0STASP0) - 실수신 62 필드
COLUMNS_H0STASP0_62 = (
    ["MKSC_SHRN_ISCD", "BSOP_HOUR", "HOUR_CLS_CODE"] +
    [f"ASKP{i}" for i in range(1, 11)] +
    [f"BIDP{i}" for i in range(1, 11)] +
    [f"ASKP_RSQN{i}" for i in range(1, 11)] +
    [f"BIDP_RSQN{i}" for i in range(1, 11)] +
    ["TOTAL_ASKP_RSQN", "TOTAL_BIDP_RSQN"] +
    [f"_EXTRA{i:02d}" for i in range(1, 18)]  # 62-45=17
)

# KRX 동시호가 (H0STANC0) - 45 fields (헤더 MKSC_SHRN_ISCD 포함)
# 8:50~9:00 예상체결가 + 총매수/매도잔량 브로드캐스트
# H0STCNT0와 거의 동일, CCLD_DVSN 대신 CNTG_CLS_CODE, VI_STND_PRC 없음
COLUMNS_H0STANC0 = [
    "MKSC_SHRN_ISCD","STCK_CNTG_HOUR","STCK_PRPR","PRDY_VRSS_SIGN",
    "PRDY_VRSS","PRDY_CTRT","WGHN_AVRG_STCK_PRC","STCK_OPRC",
    "STCK_HGPR","STCK_LWPR","ASKP1","BIDP1","CNTG_VOL","ACML_VOL",
    "ACML_TR_PBMN","SELN_CNTG_CSNU","SHNU_CNTG_CSNU","NTBY_CNTG_CSNU",
    "CTTR","SELN_CNTG_SMTN","SHNU_CNTG_SMTN","CNTG_CLS_CODE","SHNU_RATE",
    "PRDY_VOL_VRSS_ACML_VOL_RATE","OPRC_HOUR","OPRC_VRSS_PRPR_SIGN",
    "OPRC_VRSS_PRPR","HGPR_HOUR","HGPR_VRSS_PRPR_SIGN","HGPR_VRSS_PRPR",
    "LWPR_HOUR","LWPR_VRSS_PRPR_SIGN","LWPR_VRSS_PRPR","BSOP_DATE",
    "NEW_MKOP_CLS_CODE","TRHT_YN","ASKP_RSQN1","BIDP_RSQN1",
    "TOTAL_ASKP_RSQN","TOTAL_BIDP_RSQN","VOL_TNRT",
    "PRDY_SMNS_HOUR_ACML_VOL","PRDY_SMNS_HOUR_ACML_VOL_RATE",
    "HOUR_CLS_CODE","MRKT_TRTM_CLS_CODE",
]

COLUMNS_BY_TRID = {
    "H0STCNT0": COLUMNS_H0STCNT0,
    "H0NXCNT0": COLUMNS_H0NXCNT0,
    "H0STASP0": COLUMNS_H0STASP0_62,
    "H0STANC0": COLUMNS_H0STANC0,
}
