@echo off
cd /d %~dp0
set PYTHONPATH=%CD%\src;%PYTHONPATH%
REM === AUTO (RANKING API v1_국내주식-104) + WS TRACK + REAL ORDER ===
REM required env:
REM   KOREA_INVEST_APP_KEY
REM   KOREA_INVEST_APP_SECRET
REM   KOREA_INVEST_ACC_NO   (10 digits or 8-02)

REM use ranking markets: J (KRX), NX (NXT). You can do: set RANK_MARKETS=J,NX
set RANK_MARKETS=J,NX

REM how often to refresh ranking/watchlist (seconds)
set SCAN_INTERVAL_SEC=15
set WATCH_TOP_N=30

REM ranking query defaults (change if needed)
set FID_COND_SCR_DIV_CODE=20186
set RANK_SCR_CODES=20170
set RANK_DATE1_CANDIDATES=TODAY
set FID_RANK_SORT_CLS_CODE=1
set RANK_SORT_CODES=1
set FID_INPUT_ISCD=0000

REM emergency fallback symbols when ranking API returns empty
set FALLBACK_SYMBOLS=005930,000660,035420,051910,207940
REM watchlist filters
set ENTRY_BLOCK_DAYRISE_PCT=12.0
set WATCH_MIN_TR_VALUE=500000000
set WATCH_MIN_PRICE=10000
set WATCH_MAX_PRICE=500000
set WATCH_MIN_CHANGE_PCT=1.0
set WATCH_MAX_CHANGE_PCT=22.0
set WATCH_MIN_STRENGTH=110
set WATCH_MAX_STRENGTH=300
set WATCH_FILL_FROM_VOLUME_RANK=1
set VOLUME_RANK_MARKETS=J
set VOLUME_RANK_SCR=20171
set VOLUME_RANK_TOPK=120
set VOLUME_RANK_TR_IDS=FHPST01710000
set WATCH_FILL_FROM_STRENGTH=0
set STRENGTH_MARKETS=J,NX
set STRENGTH_SCR_CODES=20170,20186
set STRENGTH_TOPK=120
set WATCH_FILL_FROM_CONDITION=0
set WATCH_COND_SEQS=
set WATCH_INTEGRITY_WITH_QUOTE=0
set PREVCLOSE_WARMUP=0

REM sizing: 30% per trade
set POSITION_PCT=0.30

REM entry filters
set WINDOW_SEC=10
set ORDERBOOK_MAX_AGE_SEC=1.0
set MIN_TICKS_FOR_CALC=2

REM session presets (aggressive buy)
set OPEN_MIN_RET_PCT=0.20
set OPEN_MIN_TR_VALUE=0
set OPEN_MIN_TICK_COUNT=5
set OPEN_MIN_IMB=0.51
set OPEN_MAX_SPREAD_PCT=0.70
set OPEN_CONFIRM_SEC=0.1
set OPEN_COOLDOWN_SEC=25

set MID_MIN_RET_PCT=0.18
set MID_MIN_TR_VALUE=0
set MID_MIN_TICK_COUNT=5
set MID_MIN_IMB=0.50
set MID_MAX_SPREAD_PCT=0.75
set MID_CONFIRM_SEC=0.1
set MID_COOLDOWN_SEC=20

set CLOSE_MIN_RET_PCT=0.15
set CLOSE_MIN_TR_VALUE=0
set CLOSE_MIN_TICK_COUNT=4
set CLOSE_MIN_IMB=0.50
set CLOSE_MAX_SPREAD_PCT=0.80
set CLOSE_CONFIRM_SEC=0.1
set CLOSE_COOLDOWN_SEC=15

REM VI risk-off
set VI_GUARD_PCT=0.25
set VI_COOLDOWN_SEC=45
set VI_LIKE_RET_PCT_OPEN=3.2
set VI_LIKE_RET_PCT_MID=2.8
set VI_LIKE_RET_PCT_CLOSE=2.4

REM fallback/base (used if session preset missing)
set MIN_RET_PCT=0.20
set MIN_TICK_COUNT=5
set MIN_TR_VALUE=0
set MIN_IMB=0.50
set MAX_SPREAD_PCT=0.80
set CONFIRM_SEC=0.1
set COOLDOWN_SEC=20
REM exits
set HARD_STOP_PCT=3.5
set TRAIL_ARM_PCT=4.0
set TRAIL_DROP_PCT=3.5
set LIMITUP_GAP_TAKE_PCT=0.85

REM files
set OUT_FILE=data\ws_dump_{date}.log
set CONTROL_FILE=data\ws_control.log
set WATCHLIST_FILE=data\watchlist.txt
set WATCHLIST_DEBUG=data\watchlist_debug.log
set LEDGER_FILE=data\ledger_real.csv
set PREVCLOSE_CACHE=data\prev_close.json

REM discord alerts
set DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1469014857276850290/qvex_AKK19cczgRE7QDu-YoxrMaQu1dQkIy8_vRHJ16o61W4PkipAZ4NfV24Nim2Rk43
set DISCORD_BOT_NAME=파세경보기
set DISCORD_TIMEOUT_SEC=4
set HEALTH_CHECK_SEC=1800
set WS_STALE_SEC=20

python src\main_real.py
pause
